---
title: 'Spatial and Temporal Analysis of Reservoir Warming Trends: Assessing Geographic
  Gradients, Temporal Dynamics, and Regional Influences'
date: "2024-02-21"
output: 
  html_document:
    toc: TRUE
    toc_depth: 4
    toc_float: true
---

```{r setup, include=FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, echo = FALSE)
library(dplyr)

# read in data
df <- readr::read_csv("TMax_monthlyByStation_mblmModelStatistics.csv")
stations <- readr::read_csv("VADEQ_stationInfo.csv")

df$Month <- factor(df$Month, levels = c("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"))

# field to distinguish significant from not significant slopes
df$trend <- ifelse(df$model_pval <= 0.05, "significnant", "not significant")

# join into single df
df.spatial <- df %>%
  left_join(stations, join_by("FDT_STA_ID" == "Station_Id"))
```

## warming vs. lat/long

<br>

```{r, message = FALSE}
library(ggplot2)


# Faceting plots by month
ggplot(data = df.spatial, aes(x = Latitude, y = model_slope)) +
  geom_point(aes(shape = trend), alpha = .6) +
  geom_smooth(data = df.spatial, aes(x = Latitude,  y = model_slope),
              method = "lm") +
  facet_wrap(~factor(Month), scales = "free_y") +
  labs(title = "Monthly Warming Rates vs. Latitude",
       x = "Latitude",
       y = "Rate of Warming") +
  scale_shape_manual(values = c(1, 16)) +
  theme_minimal() +
  theme(legend.position = "top") 
```
<br>

```{r}

ggplot(data = df.spatial, aes(x = Longitude, y = model_slope)) +
  geom_point(aes(shape = trend), alpha = .6) +
  geom_smooth(data = df.spatial, aes(x = Longitude,  y = model_slope),
              method = "lm") +
  facet_wrap(~factor(Month), scales = "free_y") +
  labs(title = "Monthly Warming Rates vs. Longitude",
       x = "Longitude",
       y = "Rate of Warming") +
  scale_shape_manual(values = c(1, 16)) +
  theme_minimal() +
  theme(legend.position = "top") 

```

<br>

## warming vs monitoring span

```{r}
# determine monitoring record length
df.span <- df.spatial %>%
  mutate(monitoring_length = 
           as.numeric((lubridate::mdy(df.spatial$LAST_SAMPLE_DATE) - lubridate::mdy(df.spatial$FIRST_SAMPLE_DATE))/365)
  )


ggplot() +
  geom_point(data = df.span,
             aes(x = monitoring_length, y = model_slope,
                 shape = trend)) +
  geom_smooth(data = df.span, aes(x = monitoring_length,  y = model_slope),
              method = "lm") +
  facet_wrap(~factor(Month), scales = "free_y") +
  labs(title = "Warming Rates vs. Monitoring Span",
       x = "Monitoring Span (years)",
       y = "Rate of Warming") +  
  scale_shape_manual(values = c(1, 16)) +
  theme_minimal() + 
  theme(legend.position = "top") 

```

<br>

## warming vs. monitoring start year

```{r}
trend.df <- openxlsx::read.xlsx("data_original.xlsx", sheet = 2)

whatIneed <- trend.df[, c(2, 4:5)]

df <- df %>%
  left_join(whatIneed, join_by("FDT_STA_ID"))


ggplot() +
  geom_point(data = df,
             aes(x = MinYear, y = model_slope,
                 shape = trend), alpha = .6) +
  geom_smooth(data = df, aes(x = MinYear,  y = model_slope),
              method = "lm") +
  facet_wrap(~factor(Month), scales = "free_y") +
  labs(title = "Warming Rates vs. Initial Monitoring Year",
       x = "First Year of Monitoring",
       y = "Rate of Warming") +  
  scale_shape_manual(values = c(1, 16)) +
  theme_minimal() + 
  theme(legend.position = "top") 

```
<br>

## warming vs. midpoint of years

```{r}
df.mid <- df %>%
  mutate(midpoint = (MaxYear + MinYear) / 2)



ggplot() +
  geom_point(data = df.mid,
             aes(x = midpoint, y = model_slope,
                 shape = trend), alpha = .6) +
  geom_smooth(data = df.mid, aes(x = midpoint,  y = model_slope),
              method = "lm") +
  facet_wrap(~factor(Month), scales = "free_y") +
  labs(title = "Warming Rates vs. Monitoring Midpoint",
       x = "Monitoring Midpoint",
       y = "Rate of Warming") +  
  scale_shape_manual(values = c(1, 16)) +
  theme_minimal() + 
  theme(legend.position = "top") 

```

## warming vs level III ecoregions

```{r, message = FALSE, include=FALSE}
library(sf)

# read in ecoregions shapefile
eco.sf <- suppressMessages(st_read("ecoregions_shp"))

# transform primary df to sf object
df.spatial <- st_as_sf(df.spatial, coords = c("Longitude", "Latitude"), crs = 4326)

# convert to same crs as ecoregions
df.spatial <- st_transform(df.spatial, crs = st_crs(eco.sf))

# spatial join ecoregions to reservoir data 
eco.sf <- eco.sf %>%
  select(US_L3CODE, US_L3NAME, geometry)
ecoregions.df <- st_join(df.spatial, eco.sf)


unique(ecoregions.df$US_L3NAME)

```

```{r}

p <- ecoregions.df %>%
  group_by(US_L3NAME, Month) %>%
  summarize(mean_anomaly = mean(model_slope))

 ggplot(p, aes(x = US_L3NAME, y = mean_anomaly, fill = US_L3NAME)) +
  geom_bar(stat = "identity", position = position_dodge()) +
  facet_wrap(~factor(Month), scales = "free_y") +
  labs(title = "Mean Warming Anomaly by Ecoregion and Month",
       x = "Ecoregion",
       y = "Mean Warming Anomaly",
       fill = "Ecoregion") +
  theme_minimal() +
  theme(legend.position = "top") +
  theme(axis.text.x = element_blank())



```

